[postgres-sample]
  driver = "postgres"
  dsn = "postgres://user:password@127.0.0.1:5432/dbname?sslmode=disable"
  source_dir = [
    "./testdata/postgres/migrates",
    "./testdata/postgres/seeds"
  ]

[mysql-sample]
  driver = "mysql"
  dsn = "user:password@tcp(127.0.0.1:3306)/dbname"
  source_dir = [
    "./testdata/mysql/migrates",
    "./testdata/mysql/seeds"
  ]

[environment-variable-sample]
  driver = "postgres"
  dsn = "postgres://user:${PASSWORD}@${HOSTNAME}:5432/dbname?sslmode=disable"
  source_dir = [
    "./testdata/postgres/migrates",
    "./testdata/postgres/seeds"
  ]

[option-sample] # section name
  driver = "postgres" # database driver
  dsn = "postgres://user:${PASSWORD}@${HOSTNAME}:5432/dbname?sslmode=disable" # database dsn
  source_dir = [ # database source directorys
    "./testdata/postgres/migrates",
    "./testdata/postgres/seeds"
  ]
  up_annotation = "+goose Up" # database up command annotation
  down_annotation = "+goose Down" # database down command annotation
  version_table = "migration_versions" # versions use table name
  version_start_number = 2019060819341936 # version start number
  output_format = "JSON" # output message format
