[postgres-sample]
  driver = "postgres"
  dsn = "postgres://user:password@127.0.0.1:5432/dbname?sslmode=disable"
  source_dir = ["./data/migrates", "./data/seeds"]
  version_table = "migration_versions"

[mysql-sample]
  driver = "mysql"
  dsn = "user:password@tcp(127.0.0.1:3306)/dbname"
  source_dir = ["./data/migrates", "./data/seeds"]
  version_table = "migration_versions"
